---

all:

  hosts:

    host_proxy:
      ansible_connection: local
      ansible_host: localhost
    host_remote:
      ansible_connection: ssh
      ansible_host: localhost

  children:

    proxy_instances:
      hosts:
        host_proxy:
