---

- hosts: all

  vars:
    docker_install_compose: no
    docker_users: [
      "{{ ansible_user_id }}"
    ]

  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre_tasks

  tasks:

    - name: "Test proxy by getting file"
      import_role:
        name: get_file

    - name: "Test proxy by installing package"
      import_role:
        name: install_pkg

    - set_fact:
        pip_install_packages: [
          { 'name': 'astral', 'state': 'latest' }
        ]

    - name: Test proxy by installing pip and python modules"
      become: yes
      import_role:
        name: geerlingguy.pip

    - name: "Install Docker"
      become: yes
      import_role:
        name: geerlingguy.docker

    - name: "Configure Docker"
      become: yes
      import_role:
        name: docker-configure
      
    - name: "Run docker image"
      import_role:
        name: portainer
      
      
