---

- hosts: all

  tasks:

    - name: Set environmental settings when proxy host list exists
      block:

      - name: Configure environment
        import_role:
          name: environment-configuration


      - name: Reset ssh connection
        meta: reset_connection

      when: 1


- hosts: host_proxy

  tasks:

    - name: "Open proxy firewall"
      import_role:
        name: firewall-configuration


- hosts: all

  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') | default(omit) }}"
    https_proxy: "{{ lookup('env', 'https_proxy') | default(omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy') | default(omit) }}"
    HTTP_PROXY: "{{ lookup('env', 'HTTP_PROXY') | default(omit) }}"
    HTTPS_PROXY: "{{ lookup('env', 'HTTPS_PROXY') | default(omit) }}"
    NO_PROXY: "{{ lookup('env', 'NO_PROXY') | default(omit) }}"

  vars:
    # override geerlingguy.docker default vars
    docker_install_compose: no
    docker_users: [
      "{{ ansible_user_id }}"
    ]

    # should be able to be determined automatically and removed
    configure_for_proxy: yes
    manage_firewall: yes
    
    # local http_proxy
    http_proxy: "{{ lookup('env', 'http_proxy') | default(omit) }}"
    https_proxy: "{{ lookup('env', 'https_proxy') | default(omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy') | default(omit) }}"
    # to get remote, use {{ ansible_env.http_proxy }}

  pre_tasks:


  tasks:
  
    - name: "Run debug tasks"
      import_role:
        name: debug_tasks

    - name: "Test proxy by getting a file"
      import_role:
        name: get_file
      when: 0

    - name: "Test proxy by installing a package"
      import_role:
        name: install_pkg
      when: 0

    - name: "Set python modules for pip to install"
      set_fact:
        pip_install_packages: [
          { 'name': 'docker', 'state': 'latest' }
        ]

    - name: "Test proxy by installing pip and python modules"
      become: yes
      import_role:
        name: geerlingguy.pip
      when: 0

    - name: "Install Docker"
      become: yes
      import_role:
        name: geerlingguy.docker
      when: 0

    - name: "Configure Docker"
      become: yes
      import_role:
        name: docker-configure
      when: 0

    - name: "Run docker image"
      import_role:
        name: portainer
      when: 0