---
- hosts: proxy-node

  tasks:

    - name: "Open proxy firewall"
      import_role:
        name: firewall-configuration

- hosts: all

  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') | default(omit) }}"
    https_proxy: "{{ lookup('env', 'https_proxy') | default(omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy') | default(omit) }}"
    HTTP_PROXY: "{{ lookup('env', 'HTTP_PROXY') | default(omit) }}"
    HTTPS_PROXY: "{{ lookup('env', 'HTTPS_PROXY') | default(omit) }}"
    NO_PROXY: "{{ lookup('env', 'NO_PROXY') | default(omit) }}"

  vars:
    docker_install_compose: no
    docker_users: [
      "{{ ansible_user_id }}"
    ]

    configure_for_proxy: yes
    manage_firewall: yes
    
    # local http_proxy
    http_proxy: "{{ lookup('env', 'http_proxy') | default(omit) }}"
    https_proxy: "{{ lookup('env', 'https_proxy') | default(omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy') | default(omit) }}"
    # to get remote, use {{ ansible_env.http_proxy }}

  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre_tasks

  tasks:
  
    - name: "Test proxy by getting a file"
      import_role:
        name: get_file
      when: 0

    - name: "Test proxy by installing a package"
      import_role:
        name: install_pkg
      when: 0

    - name: "Set python modules for pip to install"
      set_fact:
        pip_install_packages: [
          { 'name': 'docker', 'state': 'latest' }
        ]

    - name: "Test proxy by installing pip and python modules"
      become: yes
      import_role:
        name: geerlingguy.pip
      when: 0

    - name: "Install Docker"
      become: yes
      import_role:
        name: geerlingguy.docker
      when: 0

    - name: "Configure Docker"
      become: yes
      import_role:
        name: docker-configure
      when: 0

    - name: "Run docker image"
      import_role:
        name: portainer
      when: 0