---

- hosts: all

  environment:

    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"

  vars:
    
    msg: |
      Environment Variables ("environment"):
      --------------------------------------
      {{ environment | to_nice_json }}

  pre_tasks:

    - debug:
        msg: "{{ msg.split('\n') }}"
        
  tasks:

    - name: "Test proxy by getting file"
      import_role:
        name: get_file
