---

- hosts: all

  vars:
    
  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre_tasks

  tasks:

    - name: "Test proxy by getting file"
      import_role:
        name: get_file

    - name: "Test proxy by installing package"
      import_role:
        name: install_pkg
