---

- name: Configure inbound Docker traffic
  become: true
  firewalld:
    zone: trusted
    interface: docker0
    permanent: yes
    state: enabled

# open port 53 on firewall to enable docker pull
- name: Set ports to allow inbound/outbound traffic
  set_fact:
    ports: "{{ docker_firewall_ports }}"
  notify: open_firewall_ports
  changed_when: true
  when: 0

- name: Configure firewall
  import_role:
    name: configure-firewall
    tasks_from: open-firewall-ports.yml
  when: 0
