---

# - name: "Check if firewalld service is running"
#   command: "systemctl status firewalld"
#   ignore_errors: yes
#   register: firewalld_service_running

- name: Configure firewall
  import_tasks: open-firewall-ports.yml
  # when: firewalld_service_running.rc == 0

- name: Ensure correct firewall settings
  import_tasks: restart-firewall.yml
  # when: firewalld_service_running.rc == 0
