---

- name: "Update apt cache"
  become: yes
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: "Remove package {{ install_package }}"
  become: yes
  package:
    name: "{{ install_package }}"
    state: absent

- name: "Install package {{ install_package }}"
  become: yes
  package:
    name: "{{ install_package }}"
    state: latest
