---

- name: "Update apt cache"
  become: yes
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: "Remove package {{ package }}"
  become: yes
  package:
    name: "{{ package }}"
    state: absent

- name: "Install package {{ package }}"
  become: yes
  package:
    name: "{{ package }}"
    state: latest
