---

- name: Create docker daemon service configuration directory
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    
 # Re-configure docker daemon service
- name: Generate docker daemon service configuration file
  become: yes
  template:
    src: docker.conf.j2
    dest: /etc/systemd/system/docker.service.d/docker.conf
  notify: restart_docker
  
# Configure docker daemon service to use proxy
- name: Generate docker daemon service proxy configuration file
  become: yes
  template:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  notify: restart_docker
  when: (http_proxy is defined) or (https_proxy is defined)

# Configure the docker daemon
# See: https://docs.docker.com/config/daemon
- name: Generate docker daemon configure file
  become: yes
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    backup: yes
  notify: restart_docker

- name: Create docker client configuration directory 
  file:
    path: "{{ ansible_user_dir }}/.docker"
    state: directory

# Configure Docker Client to pass proxy information to containers
- name: Generate docker client settings
  template:
    src: config.json.j2
    dest: "{{ docker_client_conf_dir }}/config.json"
    backup: yes
  when: (http_proxy is defined) or (https_proxy is defined)
